const cities = [
    {
      key: 1,
      name: "Toronto",
      province:"on",
      country:"ca",
    },
    {
      key: 2,
      name: "Vancouver",
      province:"bc",
      country:"ca",
    },
    {
      key: 3,
      name: "Hamilton",
      province:"on",
      country:"ca",
    },
    {
      key: 4,
      name: "Victoria",
      province:"bc",
      country:"ca",
    },
    {
      key: 5,
      name: "Oakville",
      province:"on",
      country:"ca",
    },
    {
      key: 6,
      name: "Kingston",
      province:"on",
      country:"ca",
    },
    {
      key: 7,
      name: "Waterloo",
      province:"on",
      country:"ca",
    },
  
    {
      key: 8,
      name: "Sarnia",
      province:"on",
      country:"ca",
    },
    {
      key: 9,
      name: "Brantford",
      province:"on",
      country:"ca",
    },
    {
      key: 10,
      name: "Calgary",
      province:"ab",
      country:"ca",
    },
    {
      key: 11,
      name: "Edmonton",
      province:"ab",
      country:"ca",
    },
    {
      key: 12,
      name: "Winnipeg",
      province:"mb",
      country:"ca",
    },{
      key: 13,
      name: "Kitchener",
      province:"on",
      country:"ca",
    },
    {
      key: 14,
      name: "Windsor",
      province:"on",
      country:"ca",
    },
    {
      key: 15,
      name: "Cambridge",
      province:"on",
      country:"ca",
    },
    {
      key: 16,
      name: "Milton",
      province:"on",
      country:"ca",
    },
    {
      key: 17,
      name: "Surrey",
      province:"bc",
      country:"ca",
    },
    {
      key: 18,
      name: "Ottawa",
      province:"on",
      country:"ca",
    },
    {
      key: 19,
      name: "Kelowna",
      province:"bc",
      country:"ca",
    },
    {
      key: 20,
      name: "Guelph",
      province:"on",
      country:"ca",
    },
    {
      key: 21,
      name: "Montreal",
      province:"qc",
      country:"ca",
    },
    {
      key: 22,
      name: "Peterborough",
      province:"on",
      country:"ca",
    },
    {
      key: 23,
      name: "Markham",
      province:"on",
      country:"ca",
    },
    {
      key: 24,
      name: "London",
      province:"on",
      country:"ca",
    },
    {
      key: 25,
      name: "Mississauga",
      province:"on",
      country:"ca",
    },
    {
      key: 26,
      name: "Burlington",
      province:"on",
      country:"ca",
    },
    {
      key: 27,
      name: "Barrie",
      province:"on",
      country:"ca",
    },
    {
      key: 28,
      name: "Brampton",
      province:"on",
      country:"ca",
    },
    {
      key: 29,
      name: "Oshawa",
      province:"on",
      country:"ca",
    },
    {
      key: 30,
      name: "Etobicoke",
      province:"on",
      country:"ca",
    },
    {
      key: 31,
      name: "All",
      province:"",
      country:"ca",
    },
    
  ];
  export  default cities
  